#!/sbin/busybox sh

export BOOTREC_EVENT_NODE="/dev/input/event9 c 13 73"
export BOOTREC_EVENT="/dev/input/event9"
export BOOTREC_LED_RED="/sys/class/leds/lm3533-red/brightness"
export BOOTREC_LED_GREEN="/sys/class/leds/lm3533-green/brightness"
export BOOTREC_LED_BLUE="/sys/class/leds/lm3533-blue/brightness"
export BOOTREC_FOTA_NODE="/dev/block/mmcblk0p23 b 179 23"
export BOOTREC_FOTA="/dev/block/mmcblk0p23"
